go_library(
    name = "workspace",
    srcs = [
        "workspace.go",
    ],
    visibility = [
        "//cmd/...",
    ],
    deps = [
        "//internal/logging",
        "//pkg/please",
        "//pkg/module",
    ]
)
