go_binary(
    name = "please_terraform",
    srcs = ["main.go"],
    visibility = ["PUBLIC"],
    deps = [
        "//pkg/module",
        "//pkg/provider",
        "//pkg/workspace",
        "//internal/cmd",
    ],
)
