name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag
        run: |-
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag \
            -a ${{ github.event.inputs.version }} \
            -m ${{ github.event.inputs.version }}
          git push origin --tags

      - name: Build
        run: |-
          ./pleasew build -p -v=2 \
            --arch linux_amd64 \
            //cmd/please_terraform:please_terraform

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: plz-out/bin/cmd/please_terraform/please_terraform
