name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag
        run: |-
          git tag \
            -a ${{ github.event.inputs.version }} \
            -m ${{ github.event.inputs.version }}
          git push origin --tags
