name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          ./pleasew build -p -v=2 \
            --arch linux_amd64 \
            //cmd/please_terraform:please_terraform

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: plz-out/bin/cmd/please_terraform/please_terraform
