---
name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: ./pleasew test -p -v2 //...

      - name: Run Terraform Plan
        run: ./pleasew query alltargets --include terraform_plan //example/... | ./pleasew run sequential -

      - name: Run Terraform Apply
        run: ./pleasew query alltargets --include terraform_apply //example/... | ./pleasew run sequential -a=--auto-approve -

      - name: Build
        run: |-
          ./pleasew build -p -v=2 \
            --profile release \
            //dist:release_files
